---
title: "Supplemental Results"
order: 3
---




Table S1 shows the results of the survey of the producer-scrounger literature. Search terms included "producer-scrounger" or "producer scrounger" or "producer" "scrounger". The temporal range was restricted from 1970-2023. This search was repeated using three different databases: Web of Science, SCOPUS and Biological Abstracts. The literature was then was combined and filtered to remove duplicates using article's DOI (Script 1).

Figure S1 shows the graph visualization of all variables directly and indirectly related to producer-scrounger dynamics identified in the reviewed literature. The full graph has been reduced to emphasize two groups of variables in Figure 2 and Figure 3. The variables that directly and indirectly contribute to the proportion of scrounging in a group are shown in Figure 2. The group or population level effects of the proportion of scrounging and related variables are shown in Figure 3. The complexity of the full graph indicates the interconnectedness of animals' environments, conspecifics and potential constraints in foraging. Notably, there are few environmental variables beyond resource patch characteristics such as  patch richness, distribution, and size. Social variables including relatedness, affiliations and dominance are well described. Some notable disagreements in the literature include the relationship between antipredator vigilance and scrounging behaviour [@Ranta_1996; @Ranta_1998; @Mathot_2007], age related differences in scrounging behaviour [@Teichroeb_2015; @Aplin_2017], and the contribution of learning on the frequency of scrounging behaviour [@Afshar_2015; @Aplin_2017]. 

Figure S2 shows the graph visualization of all variables directly and indirectly related to the group level effects of scrounging behaviour identified in the reviewed literature (Table S1). The variables shown are a subset of the full graph (Figure S1) to focus on group level effects. The relationships are also a subset of the full graph, where some direct relationships with proportion of scroungers are not shown to emphasize group level effects. For example, energy reserves and patch density had direct relationships with proportion of scroungers in the group (Figure 2). Some group level outcomes are related to access and availability of resources. Proportion of scroungers in a group has a negative relationship with the total quantity foraged by the group [@Vickery_2020] and the group's patch discovery rate [@Coolen_2002]. Notably, dominance has a positive relationship with forage access and both dominance and energy reserves have a positive relationship with foraging efficiency, illustrating the constraints on individuals that can influence foraging strategy beyond patch payoffs and penalties [@Caraco_1979; @Teichroeb_2015; @Lee_2016a].

Table S2 shows the counts of approaches used to study producer-scrounger dynamics in the reviewed literature (Table S1). Of the literature deemed relevant, an empirical approach was used in 62 % of studies (N = 86 / 139), an producer-scrounger model with an evolutionary game theory approach was used in 20 % of studies (N = 28 / 139) and other approaches were used in 18 % of studies (N = 25 / 139). Five articles used multiple approaches including the earliest study where Barnard and Sibly (1981) used both a producer-scrounger model and an empirical test. 

Table S3 shows the counts of species studied in empirical tests of producer-scrounger dynamics in the reviewed literature (Table S1). Three species of birds (spice finches (*Lonchura punctulata*), zebra finches (*Taeniopygia guttata*) and house sparrows (*Passer domesticus*)) make up 35 % (N = 33 / 93) of studied species. Notably, all other species were studied only three or less times with 34 species only being studied once. 

Table S4 shows the counts of taxonomic classes studied in empirical tests of producer-scrounger dynamics in the reviewed literature (Table S1). There is a majority representation of Aves. The earliest empirical tests of producer-scrounger dynamics include Barnard and Sibly's work on house sparrows (*Passer domesticus*) [-@Barnard_1981] and Giraldeau and Lefebvre's work on pigeons (*Columba livia*) [-@Giraldeau_1986]. di Bitetti and Janson's test producer-scrounger dynamics on capuchin monkeys (*Cebus apella*) [-@DiBitetti_2001] was the first empirical test of producer-scrounger dynamics on a mammalian species. Western buffalo breams (Kyphosus cornelii) were the first ray-finned fish species [@Hamilton_2003]. Finally in 2016, producer-scrounger dynamics were tested in arachnids [@Dumke_2016] and insects [@Katz_2016]. Notable vertebrate groups that are not represented in the results of this literature survey include reptiles, amphibians, jawless fishes, lobe-finned fishes and cartilaginous fishes. 


<!-- make numbers in `r` --->