# Table S2


Table S2: Approaches used in producer-scrounger dynamics literature

```{r}
#| include: false
library(gt)
```

```{r, echo = FALSE}
targets::tar_read(n_by_type) |>
	gt(caption = "Table S2: Counts of approaches in producer-scrounger dynamics literature. Approaches used in the reviewed literature (Table S1) were classified as producer-scrounger dynamic models using evolutionary game theory appproaches, empirical tests, other approaches, or not relevant. Some articles used multiple approaches therefore the total count is larger than the total number of articles reviewed. Other approaches included, for example, agent-based simulations and genetic algorithms. Approaches were deemed not relevant when they did not explicitly model or test producer-scrounger dynamics and included them solely in the article's keywords, introduction or discussion content. Counts are summarized using mean, median and total sum of counts across approaches.  
") |>
	summary_rows(columns = 'Count', fns = c('sum', 'mean', 'median'))
```
