project:
  type: book

book:
  title: "Manuscript"
  author: "Alec L. Robitaille"
  date: "2023-04-03"
  chapters:
    - index.qmd
    - manuscript/introduction.qmd
    - manuscript/results.qmd
    - manuscript/discussion.qmd
    - manuscript/references.qmd

bibliography: 'references/comprehensive-exam.bib'

format: pdf