project:
  type: website
  output-dir: public
  execute-dir: project
  resources:
    - "_targets.R"
    - "gv/why-space-use.gv"
    - "gv/term-cloud.gv"


website:
  title: "Comprehensive exam"
  navbar:
     right:
      - icon: gitlab
        href: https://gitlab.com/robitalec/comps
  sidebar:
      style: "docked"
      contents: auto

format:
  html:
    theme:
      light: flatly
    toc: true
    date-format: long
    df-print: paged

