project:
  type: book
  output-dir: pdf
  execute-dir: project



book:
  title: "Ph.D. Comprehensive Examination"
  subtitle: "In the context of frequency-dependent producer-scrounger dynamics, how would one's role affect access to available resources considering risks and conditions during habitat selection?"
  output-file: "Robitaille_Alec_PhD_Comprehensive_Examination"
  author:
    - name: Alec L. Robitaille
      affiliations: 
        - name: Memorial University
  date: "2023-04-03"
  date-format: "YYYY-MM-DD"
  chapters:
    - index.qmd
    - manuscript/introduction.qmd
    - manuscript/results.qmd
    - manuscript/discussion.qmd
    - manuscript/references.qmd

bibliography: 'references/comprehensive-exam.bib'

format:
  pdf:
    include-in-header:
      text: |
        \usepackage{lipsum}
        \usepackage{setspace}
        \doublespacing
        \usepackage[sfdefault]{carlito}
    fontsize: 12pt
    margin: 1