project:
  type: website
  output-dir: public
  execute-dir: project
  resources:
    - "_targets.R"
    - "scripts/combine-lit.R"
    - "figures/*"


website:
  title: "Comprehensive exam"
  navbar:
     right:
      - icon: gitlab
        href: https://gitlab.com/robitalec/comps
  sidebar:
      style: "docked"
      contents: auto

format:
  html:
    theme:
      light: flatly
    toc: true
    date-format: long
    df-print: kable

