project:
  type: book

book:
  title: "Manuscript"
  author: "Alec L. Robitaille"
  date: "2023-04-03"
  chapters:
    - introduction.qmd
    - results.qmd
    - discussion.qmd
    - references.qmd

bibliography: '../references/comprehensive-exam.bib'

format: pdf