project:
  type: book
  output-dir: pdf
  execute-dir: project



book:
  title: "Ph.D. Comprehensive Examination"
  subtitle: "In the context of frequency-dependent producer-scrounger dynamics, how would one's role affect access to available resources considering risks and conditions during habitat selection?"
  output-file: "Robitaille_Alec_PhD_Comprehensive_Examination"
  author: |
    | Alec L. Robitaille
    | Memorial University
    | Newfoundland and Labrador
  date: "2023-04-03"
  date-format: "YYYY-MM-DD"
  chapters:
    - index.qmd
  - manuscript/introduction.qmd
    - manuscript/results.qmd
    - manuscript/discussion.qmd
    - manuscript/conclusion.qmd
    - manuscript/objects/figure-habitat-producer.qmd
    - manuscript/objects/table-rrc-results.qmd
    - manuscript/objects/figure-into-prop-scrounge.qmd
    - manuscript/references.qmd
  appendices:
    - manuscript/boxes/box_social_foraging_theory.qmd
    - manuscript/boxes/box_habitat_selection.qmd
    - manuscript/boxes/box_individual_constraints.qmd
    - manuscript/supplemental/sup-results.qmd
    - manuscript/supplemental/figure-full-workflow.qmd
    - manuscript/supplemental/figure-group-level-effects.qmd
    - manuscript/supplemental/table-lit-results.qmd
    - manuscript/supplemental/table-n-approaches.qmd
    - manuscript/supplemental/table-empirical-n-class.qmd
    - manuscript/supplemental/table-empirical-n-species.qmd
    - manuscript/supplemental/script-1.qmd

bibliography: 'references/comprehensive-exam.bib'
csl: 'references/harvard-cite-them-right.csl'

format:
  pdf:
    include-in-header:
      text: |
        \usepackage{setspace}
        \doublespacing
        \usepackage[sfdefault,lf]{carlito}
        \usepackage{typearea}
    fontsize: 12pt
    margin: 1