project:
  type: website
  output-dir: public
  execute-dir: project
  resources:
    - "_targets.R"
    - "scripts/combine-lit.R"
    - "figures/*"


website:
  navbar:
     right:
      - icon: gitlab
        href: https://gitlab.com/robitalec/comps
  sidebar:
      style: "docked"
      contents: auto

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    date-format: long
    df-print: kable
    title: "Ph.D. Comprehensive Examamination"
    subtitle: "In the context of frequency-dependent producer-scrounger dynamics, how would one’s role affect access to available resources considering risks and conditions during habitat selection?"
    author:
      - name: Alec L. Robitaille
        affiliations:
          - name: Memorial University

