---
title: Abstract
order: 1
---


Social foraging theory examines how animal foraging behaviour is influenced by conspecifics. Individuals may choose to "produce" by independently searching for resources. Alternatively, individuals may choose to "scrounge" by following conspecifics to share or steal resources discovered by others. The dynamics of producer-scrounger behaviours are studied using evolutionary game theory models to determine optimal strategies for individuals and populations. Habitats, however, are more complex than patches of resources for individuals to share or steal from each other. Risks like predation or disturbance may force individuals to avoid habitats. Conditions like temperature or snow cover may reduce an individual's ability to forage. There is a clear potential for habitat risks and conditions as well as the presence of conspecifics to influence the costs and benefits of foraging behaviours. To investigate these influences, I reviewed the producer-scrounger literature to determine how foraging roles differ in access to available resources and how risks and conditions influence foraging behaviours. While I found few examples where risks and conditions were tested in producer-scrounger dynamics, there were many examples of constraints on individuals, such as dominance or social affiliation, influencing foraging strategies. I propose that future work establishing the influence of risks and conditions on foraging strategies must also consider the potentially confounding individual constraints. Finally, I propose an extension to the habitat selection concept of availability to incorporate role in producer-scrounger dynamics. 

