---
title: Conclusion
order: 4
---



Social foraging theory and habitat selection are related but relatively distinct bodies of literature. Whereas social foraging theory is concerned with the interdependence of individuals' foraging strategies, habitat selection is interested in the relationship between an an individuals' used and available habitats. Approaches to social foraging theory most commonly include evolutionary game theory models and empirical tests, where the outcomes are centered on observed behaviours and optimal strategies. Habitat selection analyses seek to determine species distributions, inference of selection for habitat variables and predictions of expected use of novel spatial and temporal landscapes. Despite their differences in focus and methodology, habitat selection and social foraging theory are unified by their shared interest in how animals use behaviour to balance the costs and benefits of their habitats.  I have identified that habitat selection can lend a comprehensive definition of habitat to social foraging theory, and that social foraging theory can offer a precision to the habitat selection definition of availability. 

While the producer-scrounger literature has not explicitly tested the influence of a diverse set of habitat risks and conditions (Table 1), a broad set of related variables have been identified as individual constraints (Box 3). Dominiance, relatedness and energy reserves, for example, have been shown to have large contributions to an animal's foraging strategy and their corresponding foraging success among conspecifics. In future empirical tests, risks and conditions must be carefully integrated to avoid confounding with individual constraints. In addition, more empirical tests are required on species underrepresented in the literature. Most species were only involved in one empirical test (Table S4) and entire classes of vertebrates were not represented (Table S3). Conflicts in the literature, such as the compatibility between vigilance behaviour and scrounging, and parsing the influences of age and sex from dominance on scrounging, require cross taxa review. 

The proposed extension of resource availability to consider an individual's role in producer-scrounger dynamics offers the methodological integration of social foraging theory into habitat selection analyses. As the concept of availaility in habitat selection has developed, the subset of habitat that is realistically accessible has been constrained using variables related to the animal's movement. By incorporating behaviours the distinctions between available and accessible habitats can be further refined. Measuring habitat selection within behavioural states, such as exploratory and encamped states, will reduce imprecision resulting from aggregating across differences in behaviour due to time of day, seasons of migration or reproduction. Finally, within behavioural states relevant to foraging, incorporating how foraging strategies affect access and availability will help further improve selection in producer-scrounger dynamics. 




Consider first categorizingg an animal's movement according to a particular behavioural mode, eg. exploratory or encamped. Within encamped animal telemetry dataFirs, animal's behavioural mode, eg. foraging or encamped, 





we learned that producer scrounger literature hasnt really considered risks and conditions

we learned that it is largely been tested on birds and many species have not been tested multiple times 

while there isnt a already tested relationship between habitat RRC and producer scrounger dynamics in most cases, there is a clear path forward
consider constraints and measure the influence of RRC

definition of habitat can inform future studies of producer scrounger dynamics by highlighting potentially influential variables, categorized by their expected fitness 





we also identtified a methodological connection to expand habitat selection from produycer scrounger dynamics
while the ddefinition of availability continues to be refined by considering animal's movement patterns, behaviours hahve not been as quickly adopted

we note the HMM, behavioural state approach
of which we propose should be integrated with foraging strategy 

within behavioural state, animals make different selections
eg for resting, or foraging

within behavioural states that incorporate foraging, how do foraging strategies impact availability, eg. scroungers only where nearby conspecific producers













connection between p-s and modern tracking technology


