---
title: Introduction
order : 1
---


Foraging for resources depends on the behaviour of conspecifics. Early individual foraging theory often focused on forage selection, net rate of intake, and effort or quitting time [@Stephens_1986; @Stephens_2007]. Social foraging theory considers the interdependence between a forager's strategy and that of their conspecifics [@Giraldeau_2000; Box 1]. The complexity of multiple individuals foraging from a common patch requires attention to both the density of individuals and the frequency of strategies among them [@Barnard_1981; @Vickery_1991; @Giraldeau_2000]. Social foraging theory considers a minimum criterion for sociality where animals are considered social if their benefits and costs are interdependent [@Giraldeau_2000]. Producer-scrounger dynamics are a type of social foraging model that considers two types of foraging behaviours [@Barnard_1981; @Giraldeau_2000 but see @Vickery_1991]. Producers are animals that independently search for forage patches. Scroungers follow conspecific producers to share or steal from their discovered patches. The frequency of each strategy in a group or population changes its profitability. When producers are rare, scrounging is less favorable since less patches are being discovered. When scroungers are common, producers have to divide their patches among more conspecifics patches [@Vickery_1991; @Giraldeau_2000; @Dubois_2005]. Notably, the accessibility of resources is different depending on the foraging strategy where scroungers only have access to patches made available to them by producers. 

Determining the subset of available habitat that is accessible to animals has been a methodological focus of habitat selection analyses [@Beyer_2010; @Northrup_2013; @Matthioplous_2020]. Part of this focus is due to the inherent requirement for a definition of availability to calculation selection. Preferential selection of a habitat by an animal is defined as the disproportionate use given the availability. If the measurement of available habitat is inaccurate, the measure of selection will be inaccurate. Advances in theory and computational power have offered a refined measure of availability that is constrained to variables related to animal's movement patterns [@Thurfjell_2014]. Given these, habitat selection analyses help discern the relationship between animal's movement and their selection or avoidance for particular habitats [@Matthioplous_2023, Box 2]. 

A habitat is defined as a combination of environmental variables categorized as resources, risks and conditions [@Aarts_2008; @Matthioplous_2023; Box 2]. Resources are variables that provide a benefit to an animal including forage, mating opportunities, resting sites, and nesting sites. Risks are variables that can have a negative influence on survival or contribute to perceived risk including predation, anthropogenic disturbance or harvest, and parasites. Conditions are variables that often have negative effects when they are extreme but neutral effects at average levels including temperature, humidity, salinity, and wind speed. Resources, risks and conditions influence behavioural selection of habitats and species distributions [@Matthioplous_2023]. <!-- tie into behaviour influence -->

How is foraging strategy related to access
How is foraging strategy influenced by RRC
How is availability informed by foraging strategy


Habitats are defined as a collection of environmental variables categorized as resources, risks and conditions. 




 of habitat is inaccurate, the measure of selection will Selection of habitat by animals is the disproportionate use given the ava


Considering habitat as RRC, how is access among producers and scroungers changed





Accessibility and availability are impossible to calculate is alternatively defined in habitat selection

- Habitat selection offers species distributions, model inference or predictions about habitat selection
    - Behavioural selection for habitat is based in the decision when to leave a patch and where to go next @Matthioplous_2023
    - Animal sociality is often described as a balance between advantages and disadvantages. Social foraging theory is not centred on competing causes of sociality. Rather the payoffs and penalties are directly integrated as currencies of fitness. 
- Producer scrounger dynamics
    - Approaches: game theory, empirical, other simulations
- 1. How is access to available resources determined by role?
- Conspecifics influence but so does habitat
    - Habitat = resources, risks, conditions
        - habitats under this definition allow for multiple scales of selection
    - Species-habitat associations are used to understand the relationship between
species distribution and habitats (three general goals: estimation, inference, 
and prediction)
2. How are foraging strategies influenced by habitat?
    - resources
    - risks
    - conditions
- Approach of habitat selection analyses
3. How is availability informed by behaviour, specifically p-s dynamics?
- Methods
    - Review  literature
        - Search
        - Game theory models, empirical, other
        - Resources, risks, conditions
        - Individual constraints
        - Related variables


<!-- 

## Literature searches



https://www-webofscience-com.qe2a-proxy.mun.ca/wos/woscc/summary/081aaf7e-e39b-4500-aac2-e44bcf21d3f6-78707ffd/relevance/1


+ "habitat selection"



https://www-webofscience-com.qe2a-proxy.mun.ca/wos/woscc/summary/b091d426-d8ea-4e4e-824c-3fda822b700d-7912459f/relevance/1

"producer-scrounger" OR "producer scrounger" OR producer scrounger AND 1970-2023

233 results

- 41 Giraldeau
- 12 Beauchamp G
- 10 Barta Z
- 8 Morrand-ferron J, Ranta E, Webster MM, Laland KN, Feldman MW 
- ...

Peak in 2012-2016, 2002, 2006
-->




<!--

Include figure 1


Statement of position/angle

- treating producer scrounger dynamics as occurring within habitat selection, where scrounging individuals use conspecifics to identify forage habitat
- conspecifics explicitly incorporated
- whereas habitat selection is concerned about used/available by environmental variables
- focus is on how individual behaviours and conspecifics (frequency dependence) influence availability of habitat

-->

*How do producers and scroungers differ in their access to available resources?*

-   this relates to ESSs for different densities and proportion of producers/scroungers

-   access for producers is high when density is low, because the number of available patches is high and they are more efficient than scroungers at searching for them

-   access for scroungers is low when density is low, because the overall number of producers is low and therefore low scrounging potential

-   access for producers is lower when density is high because unoccupied patches are lower

-   access for scroungers is higher when density is high because more producers have found more patches and scrounging potential is higher




<!-- from discussion -->

The objective was to answer the question: "How does one's role in frequency-dependent producer-scrounger dynamics influence access to available resources considering risks and conditions during habitat selection?". From this, I defined three goals: 1) to determine how foraging strategies differ in access to available resources, 2) to determine how risks and conditions influence foraging strategies and 3) to consider how the concept of availability during habitat selection can be extended to include foraging strategies. For 1) and 2), I identified empirical tests and model predictions in the literature that contribute to our understanding of access to available resources, and the influence of habitat risks and conditions on producer-scrounger dynamics. For 3), I propose extending the concept of availability from the habitat selection literature to incorporate role in producer-scrounger dynamics. 





