---
bibliography: '../references/comprehensive-exam.bib'
---

Access to available resources is a prerequisite for animal survival

Advantages in accessing resources can translate to an increase in 
individual fitness

At the species level, there are eg. differences in specialization/generalization
of resources, migratory behaviours, etc

Within species, individuals use modify foraging strategies to meet energetic needs
including prey/forage selection, effort/quitting time, balancing environmental
variables, eg. temperature or insect harassment, with patch quality

Foraging individuals also differ in morphological traits, eg. body size, and behaviours,
eg. dominance or aggression, that can influence foraging success 

Mobile prey represent a dynamic resource in space that requires predators to
first search out, then capture before consuming

Immobile prey, such as plants, or sedentary animals (or specific lifestages of animals), 
represent relatively static resources in space requiring search then 
potential handling 

Both mobile and immobile prey can also have temporal cycles through 
seasons of plant productivity or potential timing of antipredator behaviours / 
increased risks for prey eg. reproductive timing

Individual foraging theory emphasizes the selection of prey, net rate of intake
and attack probabilities for individuals

Social foraging theory extends individual foraging theory by considering
the complexity of multiple individuals in a common resource

The criteria for regarding animals as social in this context simply
requires interdependence of the payoffs and penalties of their strategies

Social foraging theory is grounded in evolutionary game theory and it seeks to 
determine optimal strategies given density and behaviour of conspecifics

Animal sociality is often described as a balance between advantages and disadvantages. 
Social foraging theory is not centred on competing causes of sociality. Rather
the payoffs and penalties are directly integrated as currencies of fitness. 

Payoffs can include

Penalties can include

The payoffs and penalties of different strategies are density dependent

Three kinds of social foraging behaviours are commonly defined.  
Interference represents negative impacts on conspecifics that do not
have a direct benefit to the individual and therefore do not represent 
a strategy that can be modelled as an evolutionary game

Kleptoparasitism is directly stealing indivisible food items from conspecifics

Producer-scrounger models consider two types of strategies. Producers search
for and find food patches. Scroungers do not search for patches and attempt
to steal or divide food patches with producers

Some producer-scrounger models also consider opportunists that produce and 
scrounge but at a reduced efficiency compared to the pure strategies of 
producing or scrounging

When a scrounger arrives on a food patch, models can assume either 
total information or partial information about remaining food at the patch

Food patches can be divide equally, according to arrival time on the patch 
or asymmetrical given dominance or aggression of individuals

Contests between producers and scroungers are determined by the probability 
of the scrounger winning the contest and by the energetic cost of the contest

Extensions to producer-scrounger games include memory, learning and variable
patch quality or distribution 
<!-- distribution https://pubmed.ncbi.nlm.nih.gov/19501599/ -->

Unlike information sharing models, producer-scrounger models are 
frequency dependent. The assumptions of information sharing models are 
unrealistic and have had little support in empirical tests

Access to available resources in basic producer-scrounger games depends on 
the frequency of strategies being played in the group or population

<!--At low density, scrounging is disfavored
due to low overall number of producers. At high density, scrounging becomes more
favorable given more opportunities to scrounge from producers. The inverse
is true for producers where high density is disfavored given lower available
empty patches in the environment. 
-->

<!-- optimization methods --> 
Models of producer-scrounger games show relationships between density, 
payoffs, and penalties (considering the specific goals and assumptions of 
each model) (Table 1)

Agent based simulation approaches are an alternative to solving evolutionary
stable strategies of producer-scrounger dynamics with similar results

Empirical tests of producer-scrounger dynamics are (Table 2)
<!-- diverse and support models or not diverse and somewhat disagree.. 
body size https://link.springer.com/article/10.1007/s12080-018-0375-2
-->

Differences between empirical tests and model assumptions obscure these comparisons
and experiments testing producer-scrounger dynamics are challenging to 
control and execute

Gaps from the evolutionary game theory approach include prediction of the distribution
of strategies in geographic space 
