---
title: Objects
---

## Table 1

Table 1: Producer-scrounger models

```{r}
#| echo: false
targets::tar_read(table_ps_models_compared)
```

## Table 2

Table 2: Empirical tests of producer-scrounger dynamics


## Table 3

Table 3: Comparing access to available resources for producers and scroungers

| Density/group size | Resources           | Risks             | Conditions             | Game theoretical results | Simulated results | Empirical results |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| High               | Available resources | Risks not present | Conditions neutral     |                          |                   |                   |
| Low                | Available resources | Risks not present | Conditions neutral     |                          |                   |                   |
| High               | Available resources | Risks not present | Conditions unfavorable |                          |                   |                   |
| Low                | Available resources | Risks not present | Conditions unfavorable |                          |                   |                   |
| High               | Available resources | Risks present     | Conditions neutral     |                          |                   |                   |
| Low                | Available resources | Risks present     | Conditions neutral     |                          |                   |                   |
| High               | Available resources | Risks present     | Conditions unfavorable |                          |                   |                   |
| Low                | Available resources | Risks present     | Conditions unfavorable |                          |                   |                   |

