# Object: Table 4

Table 4: Comparing access to available resources for producers and scroungers

| Density/group size | Resources           | Risks             | Conditions             | Game theoretical results | Simulated results | Empirical results |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| High               | Available resources | Risks not present | Conditions neutral     |                          |                   |                   |
| Low                | Available resources | Risks not present | Conditions neutral     |                          |                   |                   |
| High               | Available resources | Risks not present | Conditions unfavorable |                          |                   |                   |
| Low                | Available resources | Risks not present | Conditions unfavorable |                          |                   |                   |
| High               | Available resources | Risks present     | Conditions neutral     |                          |                   |                   |
| Low                | Available resources | Risks present     | Conditions neutral     |                          |                   |                   |
| High               | Available resources | Risks present     | Conditions unfavorable |                          |                   |                   |
| Low                | Available resources | Risks present     | Conditions unfavorable |                          |                   |                   |

