---
title: Results
---

## Captions

Table 1: Resources, risks and conditions identified in the producer-scrounger literature reviewed (Table S1). Examples of variables for resources, risks and conditions comprising animal's habitats were derived from Matthiopolous et al. (2023). Corresponding articles that directly investigated the influence of each variable on  producer-scrounger dynamics were listed. Articles were grouped according to approach, either producer-scrounger models using evolutionary game theory or empirical tests. 

Figure 2: Graph visualization of all variables directly and indirectly related to the proportion of scrounging behaviour identified in the reviewed literature (Table S1). The variables shown are a subset of the full graph (Figure S1) to focus on the proportion of scrounging in a group. The color of the lines indicates the nature of the relationship: blue indicates a positive relationship, red indicates a negative relationship, black indicates a neutral relationship, orange indicates a convex relationship and grey indicates subcategories. For example, group size has a positive relationship with learning (Smolla 2015), patch richness has a negative relationship with finder share (Teichroeb 2015), energy reserves has a neutral relationship with proportion of scroungers (Lee 2016a), adults and juveniles are a subcategory of age, and time of day has a convex relationship with proportion of scrounger (Barta 2000). Linetypes indicate the approach of the study that contributed this relationship where solid lines are producer-scrounger models using evolutionary game theory and dashed lines are empirical tests. For example, the relationship between group size andd learning was contributed by an evolutionary game theory model (Smolla 2015) and the relationship between patch richness and finder share  was contributed by an empirical test (Teichroeb 2015). Note that multiple lines may be drawn between the same pair of variables and when they are differently colored it indicates a disagreement in the reviewed articles. Citations for multiple articles that contributed the same approach (linetype) and nature of relationship (color) are combined in a list. Citations are always found above the line between the two variables. The graph visualization was built using GraphViz (Gansner and North 2000). 


Figure 3: Graph visualization of all variables directly and indirectly related to the group level effects of scrounging behaviour identified in the reviewed literature (Table S1). The variables shown are a subset of the full graph (Figure S1) to focus on group level effects. The color of the lines indicates the nature of the relationship: blue indicates a positive relationship and red indicates a negative relationship. For example, dominance has a positive relationship on forage efficiency (Caraco 1979), proportion of scroungers has a negative relationship with total quantity foraged by a group (Vickery 2020). Linetypes indicate the approach of the study that contributed this relationship where solid lines are producer-scrounger models using evolutionary game theory and dashed lines are empirical tests. For example, the relationship between dominance and forage efficiency was contributed by an evolutionary game theory model (Caraco 1979) and the relationship between proportion of scroungers and network centrality was contributed by an empirical test (Aplin 2017). Note that multiple lines may be drawn between the same pair of variables and when they are differently colored it indicates a disagreement in the reviewed articles. Citations for multiple articles that contributed the same approach (linetype) and nature of relationship (color) are combined in a list. Citations are always found above the line between the two variables. The graph visualization was built using GraphViz (Gansner and North 2000). 

Figure S1: Graph visualization of all variables directly and indirectly related to producer-scrounger dynamics identified in the reviewed literature (Table S1). The color of the lines indicates the nature of the relationship: blue indicates a positive relationship, red indicates a negative relationship, black indicates a neutral relationship, orange indicates a convex relationship and grey indicates subcategories. For example, dominance has a positive relationship on forage access (Caraco 1979), patch richness has a negative relationship with rate of aggression (Dubois 2003), proportion of scroungers has a neutral relationship with antipredator vigilance (Mathot 2007), time of day has a convex relationship with proportion of scroungers (Barta 2000), and juveniles and adults are subcategories of age. Linetypes indicate the approach of the study that contributed this relationship where solid lines are producer-scrounger models using evolutionary game theory and dashed lines are empirical tests. For example, the relationship between patch richness and rate of aggression was contributed by an evolutionary game theory model (Dubois 2003) and the relationship between proportion of scroungers and antipredator vigilance was contributed by an empirical test (Mathot 2007). Note that multiple lines may be drawn between the same pair of variables and when they are differently colored it indicates a disagreement in the reviewed articles. Citations for multiple articles that contributed the same approach (linetype) and nature of relationship (color) are combined in a list. Citations are always found above the line between the two variables. The graph visualization was built using GraphViz (Gansner and North 2000). 


Table S1: Review of producer-scrounger literature grouped by approaches used. Approaches used included producer-scrounger models using evolutionary game theory, empirical tests, other approaches and not relevant. For empirical tests, species and taxonomic classes were recorded. Article information also includes year of publication, journal, authors and title. Literature was obtained using a search for "producer" and "scrounger" in the titles, abstracts and keywords of articles in the databases SCOPUS, Web of Science and Biological Abstracts. Literature was filtered to remove duplicates using article's DOI (Script 1). 

Table S2: Counts of approaches in producer-scrounger dynamics literature. Approaches used in the reviewed literature (Table S1) were classified as producer-scrounger dynamic models using evolutionary game theory appproaches, empirical tests, other approaches, or not relevant. Some articles used multiple approaches therefore the total count is larger than the total number of articles reviewed. Other approaches included, for example, agent-based simulations and genetic algorithms. Approaches were deemed not relevant when they did not explicitly model or test producer-scrounger dynamics and included them solely in the article's keywords, introduction or discussion content. Counts are summarized using mean, median and total sum of counts across approaches.  

Table S3: Counts of taxonomic classes in empirical tests of producer-scrounger dynamics. Approaches used in the reviewed literature (Table S1) were classified as producer-scrounger dynamic models using evolutionary game theory appproaches, empirical tests, or other approaches. Some articles used multiple approaches. For each empirical test, species and taxonomic classes were recorded for each article. In some cases, multiple species were studied in a single article therefore these counts are occurence in articles and the total count is larger than the total number of empirical studies. Counts are summarized using mean, median and total sum of counts across taxonomic classes.  

Table S4: Counts of species in empirical tests of producer-scrounger dynamics. Approaches used in the reviewed literature (Table S1) were classified as producer-scrounger dynamic models using evolutionary game theory appproaches, empirical tests, or other approaches. Some articles used multiple approaches. For each empirical test, species and taxonomic classes were recorded for each article. In some cases, multiple species were studied in a single article therefore these counts are occurence in articles and the total count is larger than the total number of empirical studies. Counts are summarized using mean, median and total sum of counts across species.  


## Described

Table 1 shows the environmental variables considered in the producer-scrounger literature reviewed (Table S1). The variables included are derived from the definition of habitat in Matthiopolous (2023): resources, risks and conditions. Only one article examined the influence of conditions (Ha 2003). For the influence of risks, it was limited to predation in producer-scrounger models (Barta 2000, Dubois 2005, Dubois 2020), empirical tests (Bugnyar and Kotrschal 2002), and the perception of predation in empirical tests (Barta 2004, Mathot 2007, Teichroeb 2015). The remaining references examine patch related variables of the habitat's resources: patch density, richness, distribution and size. 


Figure 2 shows the graph visualization of all variables directly and indirectly related to the proportion of scrounging behaviour identified in the reviewed literature (Table S1). The variables shown are a subset of the full graph (Figure S1) to focus on the proportion of scrounging in a group. The relationships are also a subset of the full graph, where relationships to other outcome variable are excluded. For example, the relationship between patch richness and rate of aggression (Dubois 2003) is not shown because the relationship between proportion of scroungers and rate of aggression was not explicitly tested in the reviewed literature. Some variables influencing proportion of scroungers are related to access and availability of resource. Patch size (King 2009, Hansen 2016) and patch distribution (Dubois 2020, Ohtsuka 2009) had a positive relationship with proportion of scrounging whereasa patch discovery rate (Ohtsuka 2009, Lee 2016), and finder share (Barta 1998, Lee 2016) had a negative relationship with proportion of scrounging. Beyond environmental variables, many other individual constraints are found to have influences on the proportion of scrounging including dominance (Caraco_1989, Barta_1998, Bugnyar_2002, Werdenich_2002, King_2009, Lee_2016, Aplin_2017),energy reserves (Lendvai 2004, Lee 2016a), relatedness (Maathot 2010) and social affiliation (King 2009). Predation risks (and proxies to simulate predation risk) were the only form of risk considered in the reviewed producer-scrounger literature (Table 1) and there were conflicting results where Dubois's game theoretical approach (2020) predicted a negative relationship with scrounging while Barta (2004) and Mathot (2007) found a positive relationship. 


Figure 3 shows the graph visualization of all variables directly and indirectly related to the group level effects of scrounging behaviour identified in the reviewed literature (Table S1). The variables shown are a subset of the full graph (Figure S1) to focus on group level effects. The relationships are also a subset of the full graph, where some direct relationships with proportion of scroungers are not shown to emphasize group level effects. For example, energy reserves and patch density had direct relationships with proportion of scroungers in the group (Figure 2). Some group level outcomes are related to access and availability of resources. Proportion of scroungers in a group has a negative relationship with the total quantity foraged by the group (Vickery 2020) and the group's patch discovery rate (Coolen 2002). Notably, dominance has a positive relationship with forage access and both dominance and energy reserves have a positive relationship with foraging efficiency, illustrating the constraints on individuals that can influence foraging strategy beyond patch payoffs and penalties (Caraco 1979, Teichroeb 2015, Lee 2016a).



Figure S1 shows the graph visualization of all variables directly and indirectly related to producer-scrounger dynamics identified in the reviewed literature. The full graph has been reduced to emphasize two groups of variables in Figure 2 and Figure 3. The variables that directly and indirectly contribute to the proportion of scrounging in a group are shown in Figure 2. The group or population level effects of the proportion of scrounging and related variables are shown in Figure 3. The complexity of the full graph indicates the interconnectedness of animals' environments, conspecifics and potential constraints in foraging. Notably, there are few environmental variables beyond resource patch characteristics such as  patch richness, distribution, and size. Social variables including relatedness, affiliations and dominance are well described. Some notable disagreements in the literature include the relationship between antipredator vigilance and scrounging behaviour (Ranta 1996, Ranta 1998, Mathot 2007), age related differences in scrounging behaviour (Teichroeb 2015, Aplin 2017), and the contribution of learning on the frequency of scrounging behaviour (Afshar 2015. Aplin 2017). 


Table S2 shows the counts of approaches used to study producer-scrounger dynamics in the reviewed literature (Table S1). Of the literature deemed relevant, an empirical approach was used in 62 % of studies (N = 86 / 139), an producer-scrounger model with an evolutionary game theory approach was used in 20 % of studies (N = 28 / 139) and other approaches were used in 18 % of studies (N = 25 / 139). Five articles used multiple approaches including the earliest study where Barnard and Sibly (1981) used both a producer-scrounger model and an empirical test. 

Table S3 shows the counts of species studied in empirical tests of producer-scrounger dynamics in the reviewed literature (Table S1). Three species of birds (spice finches (*Lonchura punctulata*), zebra finches (*Taeniopygia guttata*) and house sparrows (*Passer domesticus*)) make up 35 % (N = 33 / 93) of studied species. Notably, all other species were studied only three or less times with 34 species only being studied once. 

Table S4 shows the counts of taxonomic classes studied in empirical tests of producer-scrounger dynamics in the reviewed literature (Table S1). There is a majority representation of Aves. The earliest empirical tests of producer-scrounger dynamics include Barnard and Sibley's work on house sparrows (*Passer domesticus*) (1981) and Giraldeau and Lefebvre's work on pigeons (*Columba livia*) (1986). Di Bitetti and Janson's test of producer-scrounger dynamics on capuchin monkeys (*Cebus apella*) (2001) was the first empirical test of producer-scrounger dynamics on a mammalian species. Western buffalo breams (Kyphosus cornelii) were the first ray-finned fish species (Hamilton and Dill 2003). Finally in 2016, producer-scrounger dynamics were tested in arachnids (Dumke et al 2016) and insects (Katz and Naug 216). Notable vertebrate groups that are not represented in the results of this literature survey include reptiles, amphibians, jawless fishes, lobe-finned fishes and cartilagenous fishes. 

