# Scratch



## Question parsed

“In the context of frequency-dependent producer-scrounger dynamics, how would one’s role affect access to available resources considering risks and conditions during habitat selection?”

- frequency-dependent
- producer-scrounger dynamics
- role
	- as a producer
	- as a scrounger
	- interaction variables
		- dominance
		- metabolic state
		- genetic relatedness
		- spatial position in group
		- learning
		- personality
		- individual differences
- access to
- available 
- resources
- risks
- conditions
- habitat selection


---

<!--
## Literature results

### Models

- Strategies
	- Producers, scroungers
	- Retaliators where finder can retaliate if joiner escalates (Dubois_2007)



- Finder's share
	- Increase finder's share leads to a decrease in proportion of scroungers (Barta_1998) (Lee_2016)
	- Finder's share allows producers to always aggressively defend clumps (Dubois_2005)
	- (also under Patch departure) A producer should leave a patch earlier than a scrounger if the producer has a finder's share (Rita_1997)
	
- Contests
	- Differences between individuals in valuing resources leads to fights mainly occuring between strong individuals or weak individuals (Broom_2014)
	- Convex cost functions correspond to risk of injury or lost energy and concave cost functions correspond to time costs eg exposure of predation risk (Broom_2015)
	- (also under Finder's share) Producers should always defend clumps given their advantage already having the finder's share (Dubois_2005)
	- (also under Patch density) Where patches are dense, scrounging is disfavored because of the time invested in contests (Dubois_2005)


- Aggression
	- Rate of aggression increases with group size (Caraco_1979)
	- Aggression should decrease as the density and richness of food clumps increases (Dubois_2003)
	- Costs of aggression increase with increasing predation pressure and so the rate of aggression should decrease (Dubois_2005)


- Predation
	- (also under Aggression) Costs of aggression increase with increasing predation pressure and so the rate of aggression should decrease (Dubois_2005)
	- Lower predation risk should lead to a decrease in scrounging (Dubois_2020)
	- (also under Vigilance) Scroungers may provide antipredator vigilance and contribute to dilution effect (Ranta_1996) (Ranta_1998)


- Sharing
	- Some animals share food clumps without any overt aggression possibly due to iterated play among familiar players (Dubois_2003)
	- When retaliator strategy is included, there is widespread sharing predicted in habitats clumped with intermediate richness (Dubois_2007)
	- When information asymmetry between producers and scroungers is incorporated, conditions for sharing are more easily met (Dubois_2007)
	- Sharing should be more common when resource heterogeneity leads to increased scrounger uncertainty (Dubois_2007)


- Vigilance 
	- Increased group size leads to decreased average vigilance (Caraco_1979)
	- Scroungers may provide antipredator vigilance and contribute to dilution effect (Ranta_1996) (Ranta_1998)


- Joining distance
	- Joining distance should increase with decreasing density of foragers, increasing speed of movement, increasing difficulty in finding undiscovered food patches and decreasing speed at which patches are consumed (Ruxton_2005)


- Depletability
	- Discovered patches are more heavily exploited when patches are hard to find (Ruxton_2005)


- Dominance
	- Similar dominance, individuals should similarly play scrounger (Barta_1998)
	- Asymmetrical dominance, dominant individuals should play scrounger more often (Barta_1998)
	- Dominance increases foraging efficiency and access to forage (Caraco_1979)
	- Dominant individuals prefer social foraging while subordinate individuals prefer solitary foraging (Caraco_1989) (Lee_2016)
	- Scrounging can be an exclusive strategy of dominant individuals depending on resource monopolizability (Lee_2016)
	- If patches are distributed in clumps, dominant individuals will be able to exploit most patches by following subordinates (Caraco_1989)
	
	
- Time of day
	- Around dawn and dusk, individuals should play scrounger more often due to low energy reserves (Barta_2000)
	- Around midday, individuals should play producer if they are near or above critical reserve level because if they are successful they can more quickly switch to resting and avoid predation hazard (Barta_2000)
	
	
- Interference
	- Interference between individuals reduces average intake rate and increases variation in intake rate across foragers (Beauchamp_1997)
	
	
- Group size
	- At larger group sizes, scrounging should be more likely and when there are few foragers, scrounging should be rare (Beauchamp_2000a) (Dubois_2005)
	- (also under Patch finding rate) When probability of finding patches decreases with increasing group size, number of scroungers should increase (Dubois_2020)
	- (also under Patch finding rate) When probability of finding patches increases with increasing group size, number of scroungers should decrease (Dubois_2020)

	
- Patch richness
	- In habitats with poorer patches, scrounging should be less likely (Beauchamp_2000a)
	- Increasing patch richness will increase scrounger's share and the proportion of scroungers will increase (Dubois_2005)
	- (also under Sharing) When retaliator strategy is included, there is widespread sharing predicted in habitats clumped with intermediate richness (Dubois_2007)
	- (also under Patch distribution) If patches are distributed in rich, clumps, scrounging should increase (Dubois_2020)
	
	
- Patch density
	- At higher patch densities, the producer's patch finding rate should increase (Dubois_2005)
	- At higher patch densities, the rate of scrounging should decrease as the temporal costs of contests makes scrounging less profitable (Dubois_2005)


- Patch distribution
	- (also under Dominance) If patches are distributed in clumps, dominant individuals will be able to exploit most patches by following subordinates (Caraco_1989)
	- If patches are distributed in rich, clumps, scrounging should increase and if patches are evenly distributed, producing should increase (Dubois_2020) (Ohtsuka_2009) 
	

- Patch finding rate
	- (also under Patch density)  At higher patch densities, the producer's patch finding rate should decrease (Dubois_2005)
	- When probability of finding patches decreases with increasing group size, number of scroungers should increase (Dubois_2020)
	- When probability of finding patches increases with increasing group size, number of scroungers should decrease (Dubois_2020)
	- Decreased patch finding rate reduces the costs of solitary foraging and scrounging is less common (Lee_2016)
	- Patch finding rate strongly influences frequency of producers (Ohtsuka_2009)
	- Patch finding rate increases with the number of producers (Rita_1997)
	
	
- Patch departure
	- A producer should leave a patch earlier than a scrounger if the producer has a finder's share (Rita_1997)
	
- Resource monopolizabilitu
 	- Easily monopolized resources

- Producer scrounger models
	- Producer priority where scrounging reduces producer's food intake but does not depend on the number of scroungers in the group (Caraco_1991)
	- Scramble competition where producer's food intake decreases with the number of scroungers (Caraco_1991)


- Learning
	- Early success may lead to individuals not adapting strategy to changing environments (Beauchamp_2000a)
	- Learning never evolves to fixation and at a stable equilibrium there is a mixture of fixed and learning players (Dubois_2010)
	- Social learning is favored when competition is weak (Smolla_2015)
	- If competition is strong, social learning is favored when resource quality is highly variable and there is low environmental turnover (Smolla_2015)

	
- Information
	- Extra information held by producers can be both beneficial and harmful (Broom_2016). 
	- Information not available to scrounger in situations where resources are not immediately visible eg. concelead nests, or where contest occurs quickly after patch is discovered and before producer has time to evaluate it (Broom_2016)
	- Producers should fight for resources when costs of contests are high or scrounger has a small change of winning the contest eg. if patch is easily defended (Broom_2016)
	- When scrounger's potential cost is small compared to the value of the patch or if the scrounger has a high change of winning, the scrounger should always fight (Broom_2016)


- Relatedness
	- Increased relatedness can lead producers to being more tolerant of scrounging relatives (Mathot_2010)


- Population
	- Scrounging can act as a population regulator by reducing population level foraging efficiency and intake rate and allowing larger population sizes of predators (Coolen_2007)
	- Social foraging can stabilize one prey and two prey systems when scrounging is prevalent in predators (Toyokawa_2017) (Vickery_2020)
	- Scrounging can lower the growth rate of a population (Toyokawa_2017)
	- Scrounging can allow prey resources to persist at higher densities than if scrounging was absent (Toyokawa_2017) (Vickery_2020)
	- Presence of scroungers in a predator can reduce the total amount of resource acquired by the group (Vickery_2020)
	- Presence of scroungers in a predator can limit group size (Vickery_2020)
	- Presence of scroungers in a predator can limit a predator's ability to outcompete other species promoting stability and species diversity (Vickery_2020)
	- Scrounging will not stability population dynamics, food chains and competitor interactions under all cases, if scrounging is too prevalent it can push the population to extinction  	- Other factors such as food abundance, variations in weather, predators and parasites may have stronger effects that can completely obscure the effects of scrounging on populations (Vickery_2020)
	

### Empirical


- Interspecific social information
	- Kane_2014
	- (also under Predation risk) Scrounging more common when interspecific competition for food with high predation risk individual (wolf) versus boar (Bugnyar_2002)


- Strategy specialization
	- Stable dimorphic distribution of producers and scroungers (Aplin_2017)
	- Individuals likely to use both strategies (Ha_2003)
	
	
- Sex
	- Females were more likely to scrounge (Aplin_2017) 
	- Males were more likely to produce (Aplin_2017)
	- Air temperature, time of day, season (breeding vs nonbreeding), age or sex did not influence the probability of retaining prey (Ha_2003)
	- Females scrounged from males when pregnant (King_2009)
	- Dominant females scrounged from subordinate neighbors with whom they had a strong social affiliation (King_2009)

- Age
	- Adults were more likely to produce (Aplin_2017)
	- Juveniles were more likely to scrounge (Aplin_2017)
	- (also under Sex) Air temperature, time of day, season (breeding vs nonbreeding), age or sex did not influence the probability of retaining prey (Ha_2003)
	- No effect of age (Teichroeb_2015)
	
- Dominance
	- Male dominants more likely to produce (Aplin_2017)
	- Dominants took the role of scrounger and subordinates the role of producer (Werdenich_2002)
	- Scrounging dominants were more likely to displace conspecifics while stealing was more likely for subordinates (Bugnyar_2002)
	- (also under Sex) Dominant females scrounged from subordinate neighbors with whom they had a strong social affiliation (King_2009)
	- (also under Environmental factors) Wind exposure as a proxy to manipulate overnight energy expenditure lead dominants to scrounge more often and subordinates only marginally increase scrounging (Lendvai_2004)
	- Dominant individuals obtained more food than subordinates (Teichroeb_2015)
	- Dominant individuals obtained a larger share when producing than scrounging, balancing predation risk with food acquisition (Teichroeb_2015)
	- Finder's share increased with dominance (Teichroeb_2015)

- Social affiliation
	- Mating pairs may have contributed to male tolerance of female scroungers (Aplin_2017)
	- Scroungers had high network centrality (Aplin_2017)
	- Sharing observed when dyads of ravens were at different stages of pair bonding eg mutual preening (Bugnyar_2002)
	- (also under Sex) Dominant females scrounged from subordinate neighbors with whom they had a strong social affiliation (King_2009)

- Predation risk
	- Scrounging was more common further from cover than close to it (Barta_2004)
	- Scrounging more common when interspecific competition for food with high predation risk individual (wolf) versus boar (Bugnyar_2002)
	- Wing load manipulation (by clipping primary flight feathers) as a proxy for perception of vulnerability to predation increased time vigilant (Mathot_2007)
	- Wing load manipulation as proxy for vulnerability to predation increased scrounging but cannot distinguish compatibility of scrounging and antipredator vigilance, or scrounging due to spatial position within a group (Mathot_2007)


- Vigilance
	- Scrounging not simply explained by antipredator vigilance, alternatively may be due to scrounging being a variance-averse strategy or favored strategy when energy reserves are low  (Barta_2004)
	- No compatibility between scrounging and antipredator vigilance (Coolen_2003)
	- (also under Predation risk) Wing load manipulation (by clipping primary flight feathers) as a proxy for perception of vulnerability to predation increased time vigilant (Mathot_2007)
	- (also under Predation risk) Wing load manipulation as proxy for vulnerability to predation increased scrounging but cannot distinguish compatibility of scrounging and antipredator vigilance, or scrounging due to spatial position within a group (Mathot_2007)


- Resource availability
	- At low and intermediate resource availability, scrounging is not favored after a 30s finder's share (Kok_2017)
	- At high resource availability, scrounging is favored up to 120s (Kok_2017)

- Finder's share
	- (also under Resource availability) At low and intermediate resource availability, scrounging is not favored after a 30s finder's share (Kok_2017)
	- (also under Resource availability) At high resource availability, scrounging is favored up to 120s (Kok_2017)
	- Finder's share decreases with patch size (Hansen_2016)
	- Finder's share decreased with forager density (Hirsch_2019)
	- (also under Dominance) Finder's share increased with dominance (Teichroeb_2015)
	- Finder's share decreased with increasing patch richness (Teichroeb_2015)
	
- Handling time
	- Prey size and longer handling time resulted in higher likelihood of conspecific stealing (Ha_2003)

- Environmental factors
	- (also under Sex) Air temperature, time of day, season (breeding vs nonbreeding), age or sex did not influence the probability of retaining prey (Ha_2003)
	- Wind exposure as a proxy to manipulate overnight energy expenditure lead dominants to scrounge more often and subordinates only marginally increase scrounging (Lendvai_2004)
	

- Energy reserves / fed or fasted
	- Rates of strategy use did not differ depending on fed and fasted states in sparrows (Lee_2016a)
	- Fasted sparrows stayed longer on the ground (Lee_2016a)
	- Fasted sparrows discovered more patches and consumed more food than fed sparrows (Lee_2016a)
	- (also under Vigilance) Scrounging not simply explained by antipredator vigilance, alternatively may be due to scrounging being a variance-averse strategy or favored strategy when energy reserves are low (Barta_2004)

- Spatial position
	- Scroungers more commonly found towards center of group, producers towards edges of group (Flynn_2001) (King_2009)
	- Groups with more scroungers tended to be more compact and densely grouped (Flynn_2001)
	- Patch finding rate increased for individuals at the front edge of the group (Hirsch_2019)
	- Foraging success was higher for individuals at the back of the group where fewer conspecifics joined (Hirsch_2019)


- Relatedness
	- Related finches had higher frequencies of scrounging than unrelated finches (Mathot_2010)


- Learning
	- As individuals have more experience in variable environments, they increase proportion of scrounging (Afshar_2015)
	- Individuals that learned the task faster were less likely to scrounger (Aplin_2017)
	
- Group size
	- Larger groups had a higher proportion of scroungers (Alfaro_2021) (Aplin_2017) (Barta_2004) (Coolen_2002)
	- (also under Finder's share) Finder's share decreased with forager density (Hirsch_2019)
	- At larger group sizes, energy intake and probability of obtaining a fish declined (Belisle_1998)
	
- Resource depletability
	- Larger groups required less time to deplete resources (Alfaro_2021)
	
- Patch finding rates
	- More scroungers resulted in a lower patch finding rate for the group (Coolen_2002)
	- (also under Spatial position) Patch finding rate increased for individuals at the front edge of the group (Hirsch_2019)

- Patch size
	- If patches are large, scrounging should be more frequent (Hansen_2016) (King_2009)
	- If patches are small, solitary foraging should be more frequent (Hansen_2016)
	
- Patch richness
	- (also under Finder's share) Finder's share decreased with increasing patch richness (Teichroeb_2015)
	
- Variance strategies
	- Variance-averse foragers prefer scrounging as it is less sensitive to patch quality variance (Afshar_2015)
	- (also under Vigilance) Scrounging not simply explained by antipredator vigilance, alternatively may be due to scrounging being a variance-averse strategy or favored strategy when energy reserves are low (Barta_2004)

- Arrival time on patch
	- Individuals that arrived earlier on the patch were less likely to scrounge (Aplin_2017)
	- 

- Payoffs
	- Payoffs were higher for producers in all environmental conditions, likely due to body size and foraging efficiency (Hansen_2016)


- Group formation
	- By being attracted to producers, scroungers induce group formation (Belisle_1998)
-->


---

## Old outline

## Foraging with others

*What are the costs, benefits of sociality with respect to foraging?*

-   positives

    -   foraging benefit

    -   conserving energy, heat

-   negatives

    -   reduced local food supply

    -   interference

    -   kleptoparasitism

Related,

-   positives

    -   predator dilution, vigilance

-   negatives

    -   increased attack rate

    -   disease/parasite load

## Social foraging theory

Economic interdependence of payoffs and penalties for multiple foragers

-   *How does social foraging theory differ from individual foraging theory?*

-   *What is the chronological history of literature preceding social foraging theory that brings us to producer-scrounger dynamics?*

Criterion of sociality

Approaches

-   observational, comparative

-   optimization

    -   Evolutionary game theory

        -   Evolutionary stable strategies

        -   Nash equilibrium

Assumptions

-   strategies

    -   *how do strategies relate to alleles, phenotypes, and plasticity?*

-   populations

    -   finite or infinite

-   play

    -   repeated or single round

    -   information: uninformed or informed play

-   games

    -   symmetric

    -   discrete

Classes of behaviours among social foragers

### Producer-scrounger dynamics

-   *How are producer-scrounger dynamics defined and what are their assumptions?*

-   

#### Assumptions

-   producers search for food

-   handling time is minimal

-   one or more scroungers find food after producer

-   scroungers can steal, or share and divide food with producer

##### Information

How does assumption of information influence ESS of producer scrounger games

##### Extras

Memory

#### Interactions between strategies

-   How do producers/scroungers/opportunists interact?

#### Related models

Kleptoparasitism

Interference

Information transfer models

-   How do information transfer models differ from producer-scrounger models?

## Habitat selection theory

Species-habitat associations

-   *How are habitats defined?*

    -   resources

    -   risks

    -   conditions

-   *What is the relationship between habitat and fitness?*

    -   Dynamic mechanisms

        -   Habitat selection

            -   individual level

            -   behavioural selection

                -   patch departure rules

                -   where to go

        -   Demographic sorting

            -   population level

## Influence of producer-scrounger dynamics on habitat selection given risks and conditions

The dynamic mechanism for habitat selection at the individual level is behavioural selection. It is comprised of patch departure rules or giving up rates and the decision where to go next. Habitats are defined in terms of resources, risks and conditions. Environmental variables corresponding to these three can have complex interactions.

Producer-scrounger dynamics consider the payoffs and penalties of strategies given the density of conspecifics and their corresponding strategies. A strategy whose fitness cannot be improved given the current environment and set of conspecifics' strategies or a strategy that resists the invasion of a rare alternative is an evolutionary stable strategy.

Risks are integrated differently in producer-scrounger dynamics and habitat selection. Predation risk, for example, is directly incorporated into the penalty for each strategy in a producer-scrounger game. For habitat selection, predation risk would make up one of the relevant environmental variables under the risk category that define a habitat, with an expected negative relationship with fitness.

*How are conditions considered for producer-scrounger dynamics other than extreme conditions that represent potential penalties?*

For habitat selection, conditions form a subset of the environmental variables that make up a habitat.

*How do producers and scroungers differ in their access to available resources?*

-   this relates to ESSs for different densities and proportion of producers/scroungers

-   access for producers is high when density is low, because the number of available patches is high and they are more efficient than scroungers at searching for them

-   access for scroungers is low when density is low, because the overall number of producers is low and therefore low scrounging potential

-   access for producers is lower when density is high because unoccupied patches are lower

-   access for scroungers is higher when density is high because more producers have found more patches and scrounging potential is higher

## Ideal vs available

The goal is to determine how risks and conditions of habitats influence access to available resources for individuals in frequency dependent producer-scrounger dynamics

-   *Can this be rephrased/clarified?*

### Ideal

The ideal data for relating risks and conditions during habitat selection to producer-scrounger dynamics is a controlled experiment:

-   long term observations of multiple tanks

-   tanks differ in their density

-   areas in tanks have habitats that have a measurable influence on fitness or a relevant proxy

-   habitats are not depletable

-   within habitats, food is available on patches that require some degree of searching. food is not freely available

-   vary risks across habitats

-   vary conditions across habitats

1.  record individuals in tanks
2.  tag individuals through time as producers or scroungers
3.  identify habitat selected by individuals along with associated risks and conditions
4.  repeat observations of individuals
5.  compare results across tanks with different densities
6.  compare results across habitats with different risks, conditions

### Available

Game theoretical model of producer-scrounger dynamic where resources, risks and conditions of the habitat are integrated into the payoffs and penalties

-   *Alternative?*

### Difference

-   *How do the ideal and available differ?*

-   *Why do they differ?*

-   *How can the available approach answer the question?*




---

## Actions
actions: 

A. frequency dependent producer-scrounger dynamics model incorporating risks and 
conditions of habitat
B. social habitat selection model of simulated data extending from individuals
were together in X habitat to producer scrounger / leader into patch and
follower 


requires: 

 

Species habitat associations are used for: 
- spatial estimation of density
- inference about why species occur in particular locations
- prediction of species distribution in a new time and/or space


Scale 




## Currencies
- Frequency independent (Stephens Krebs)
	- Max
	- Min
- Frequency depedent (Maynard Smith 1982)
	- Stability

## Fitness
Allee effects

### Negative
Parasite load

## Social foraging theory
### Producer-scrounger dynamics
"Scrounging payoffs are negatively frequency dependent"

## Habitat
- resources
- risks
- conditions
### Resources
Resources
- depletable
- not



## Learning
unpredictable resources

## Memory



## Niche
### Fundamental niche
### Realized niche

## Information
Imperfect information

## Scale

### Levels
- Individual
	- Stephens Krebs
- Dyad, group
	- SFT
	- Producer scrounger
- Species, populations
	- SHA
	- Habitat selection
	- SDM
- Multispecies
	- SHA

### Individual
- mobility
- spatial scales of perception

## Game theory
Rules for game theory eg 2.1.3.3

## Plasticity

## Individual differences

## Outcomes
ESS
Fitness
Population dynamics

## Approach
### Mechanistic
Social foraging theory
Explicit consideration of payoffs and penalties

### Empirical
Species distribution models, species habitat associations




## Literature searches



https://www-webofscience-com.qe2a-proxy.mun.ca/wos/woscc/summary/081aaf7e-e39b-4500-aac2-e44bcf21d3f6-78707ffd/relevance/1


+ "habitat selection"



https://www-webofscience-com.qe2a-proxy.mun.ca/wos/woscc/summary/b091d426-d8ea-4e4e-824c-3fda822b700d-7912459f/relevance/1

"producer-scrounger" OR "producer scrounger" OR producer scrounger AND 1970-2023

233 results

- 41 Giraldeau
- 12 Beauchamp G
- 10 Barta Z
- 8 Morrand-ferron J, Ranta E, Webster MM, Laland KN, Feldman MW 
- ...

Peak in 2012-2016, 2002, 2006
