# Table 1

```{r}
#| include: false
library(targets)
library(gt)
```

```{r, echo = FALSE}
tar_read(rrc_results) |>
	gt(rowname_col = 'Variable',
     groupname_col = 'Type',
		 caption = "Table 1: Resources, risks and conditions identified in the producer-scrounger literature reviewed (Table S1). Examples of variables for resources, risks and conditions comprising animal's habitats were derived from Matthiopolous et al. (2023). Corresponding articles that directly investigated the influence of each variable on  producer-scrounger dynamics were listed. Articles were grouped according to approach, either producer-scrounger models using evolutionary game theory or empirical tests. Counts are summarized using sum within variable type and total sum across variable types.") |>
	tab_options(row_group.as_column = TRUE,
				summary_row.background.color = 'grey90',
				grand_summary_row.background.color = 'grey90') |>
	tab_style(  
		style = list(
      cell_text(color = 'white')
		),
		locations = cells_body(
			columns = 'Empirical test',
      rows = is.na(`Empirical test`)
    )) |>
		tab_style(  
		style = list(
      cell_text(color = 'white')
		),
		locations = cells_body(
			columns = 'Producer scrounger model',
      rows = is.na(`Producer scrounger model`)
    )) |> 
	summary_rows(groups = TRUE, columns = 'Count', fns = 'sum', formatter = fmt_integer) |>
	tab_style(  
		style = list(
      cell_text(color = 'white')
		),
		locations = cells_body(
			columns = 'Count',
      rows = Count == 0
    )) |>
	grand_summary_rows(columns = 'Count', fns = 'sum', formatter = fmt_integer)
```

