project:
  type: website
  output-dir: ../public

website:
  page-navigation: true
  reader-mode: true
  repo-url: https://gitlab.com/robit.a/comps
  #repo-actions: [edit, issue]
  navbar:
    title: 'Comps'
    right:
      - icon: gitlab
        href: https://gitlab.com/robit.a/comps
  sidebar:
    contents:
      - index.qmd
      - topics.qmd
      - books.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
