---
title: "Box 2: Habitat Selection"
---


- Habitat selection, use /  available
- Habitat as environmental variables (resources, risks, conditions)
- Relationships between fitness and resources, risks and conditions (graphs)
- Examples of resources, risks and conditions from Matthiopolous 2023
- Examples of resources, risks and conditions from habitat selection literature


dynamic mechanisms influencing the relationship between fitness and species distribution

- demographic sorting at the population level
- habitat selection at the individuall level (behavioural selection)
    - voluntary movement composed of 
        - patch departure rules or giving up rates
            - marginal value theorem
            - intake rate
            - learning
            - information
            - environmental predictability
        - decision where to go
            - sensory perception
            - spatial memory
            - conspecific information

   

Mayor multiscale selection


conditional nature of preference


while AIC is often recommended for evaluating alternative models [@Thurfjell_2014], model selection via AIC should only be used when the goal is to determine the most predictive model and not in cases where the model is used to provide inference about covariates causally influencing use and selection Stat rethink. adding more variables, and adding confounding variables can improve predictive performance and so selecting models for inference should be based on an understanding of the causal structure and not predictive performance of models

- Distance to nearest road
- Distance to nearest road (squared)
- Aspen stand (binary)
- Forest stand (binary)
- Forest stand (proportion)
- Steep slope
- Aspend stand (binary) * wolf index cubed
- Forest stand (binary) * wolf index cubed
- Wolf index cubed

Fortin_2005

dag {
bb="-4.948,-4.048,6.275,3.622"
aspen_stand [exposure,pos="0.463,-3.409"]
dist_road [exposure,pos="-3.036,-2.274"]
dist_road_sq [exposure,pos="-4.013,-0.054"]
forest_prop [exposure,pos="2.474,0.198"]
forest_stand [exposure,pos="0.910,2.305"]
steep_slope [exposure,pos="-1.404,2.983"]
use [outcome,pos="-0.743,-0.223"]
wolf_index [exposure,pos="2.517,-1.028"]
aspen_stand -> use
dist_road -> dist_road_sq
dist_road -> use
dist_road_sq -> use
forest_prop -> forest_stand
forest_prop -> use
forest_prop -> wolf_index
forest_stand -> use
steep_slope -> forest_stand
steep_slope -> use
wolf_index -> use
}



## (Species-habitat associations) How is the relationship between animals and their environments measured? What elements of this theory could be incorporated into social foraging?

<!-- Point to Box Habitat Selection --> 

Species-habitat associations are used to understand the relationship between
species distribution and habitats (three general goals: estimation, inference, 
and prediction)

Habitats are as the combination of three kinds of environmental variables:
resources, risks and conditions

Resources are examples

Risks are examples

Conditions are examples
<!-- how does an animal select for conditions? -->

The diversity of individuals relationships with resources, risks and conditions 
are complicated further by their two-way and three-way interactions  


>

### Confounds (Why is habitat selection theory more complicated than observing where animals are present/absent?)

There are a number of confounds that cloud the relationship between
species density and fitness

Imperfect information 

Dynamic environments

Colonization credit 

Extinction debt

Site fidelity

Landscapes of fear




The dynamic mechanism for habitat selection at the individual level is behavioural selection. It is comprised of patch departure rules or giving up rates and the decision where to go next. Habitats are defined in terms of resources, risks and conditions. Environmental variables corresponding to these three can have complex interactions.


Risks are integrated differently in producer-scrounger dynamics and habitat selection. Predation risk, for example, is directly incorporated into the penalty for each strategy in a producer-scrounger game. For habitat selection, predation risk would make up one of the relevant environmental variables under the risk category that define a habitat, with an expected negative relationship with fitness.